### ISSUE TITLE
US 03.01.01 As an owner, I want to define tags that can be used to categorize items.

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#100]
We are creating a tag class that will hold the Tag Information. It will be attached to an activity where the user can define new tags, and select from current tags to attach them to a desired item

This system will also allow for the user to sort and filter by tags, but that will be addressed by different issues

This issue will be primarily the creation of a tag. its functionality will be concidered in other issues

Updates:

**Comment by Silin5** [comment]
Finished!

We created Tag and TagsManager Classes to allow for the creation and management of tags. Tag represents individual tags, and TagsManager handles the overall management of tags across items.

We created AddTagActivity to provide a user interface for adding new tags to items. It interacts with TagsManager to add the created tags to the corresponding items.
