### ISSUE TITLE
US 03.03.01 As an owner, I want to select items from the list of items and apply one or more tags to the selected items.

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#101]
This will be implemented once 03.02.01 is implemented, as that will allow us to create our tags

We have a Tag Button on the view item page, where the user will be able to view all the current tags (or create new tags), and attach them to a desired item.

This will most likely get broken up into a few sub issues

Updates:

**Comment by Silin5** [comment]
Finished!

ViewItemActivity and AddItemActivity have been set up to launch ItemTagsActivity, which is where we manage tags for a specific item. In these activities, we correctly extract the item's identifier (itemId) and pass it to ItemTagsActivity.

ItemTagsActivity is the central activity where we can view and manage tags for a specific item. It should list all tags associated with the item and allow for adding new tags via AddTagActivity and removing existing tags.

**Comment by Silin5** [comment]
Things get done:
    -Modify HomePageAdapter to Support Selection Mode.
    -Update HomePageActivity for Selection and Tag Application.
    -Created a dialog for the user to choose tags to apply.
Things need to be done:
    -setup firestore
    -TagSelectionDialog testing
