### ISSUE TITLE
US 03.02.01 As an owner, I want to specify one or more tags for an item.

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#102]
This will be very much inter twined with Adding a Tag to an item. 

We will be modifying the itemClass to hold an ArrayList<Tag> rather than a single tag

This way, we can simply append to this list to add multiple tags to the item

**Comment by Silin5** [comment]
Finished!

ViewItemActivity and AddItemActivity have been set up to launch ItemTagsActivity, which is where we manage tags for a specific item. In these activities, we correctly extract the item's identifier (itemId) and pass it to ItemTagsActivity.

ItemTagsActivity is the central activity where we can view and manage tags for a specific item. It should list all tags associated with the item and allow for adding new tags via AddTagActivity and removing existing tags.
