### ISSUE TITLE
US 03.04.01 As an owner, I want to sort the list of items by tags.

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#103]
This is a lower priority Story, is it requires both fully functional tag system, along with the sorting system. so for the time being it will be slightly further back on the priority list.

However, once we get it set up, we plan to make it work similair to all the other sorting types, however we will be ensuring to loop through every Tag the item may have (to cover the cases that an item has multiple tags)

**Comment by vinuyakarl** [comment]
Milestone 1: Able to sort by tags, if items have tags, it would get its best tag
