### ISSUE TITLE
Create UI for the Items (views and editing)

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#36]
This is the main page where we can view the details of the item, and edit parts of the item

**Comment by vinuyakarl** [comment]
First milestone: View UI is now done, users can click on an item from the homepage and be able to see its properties

**Comment by vinuyakarl** [comment]
Second milestone: Editing can be done when the edit button is clicked from the UI. Users can edit an item's properties.

**Comment by CohenCalvert** [comment]
UI for the Item has been created and is functional!
