### ISSUE TITLE
Update UML, CRC, and Storyboard

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#52]
Based off of TA feedback, we will be updating various aspects of the UML, CRC, and Storyboard Diagrams

Primarily CRC and UML, we were missing classes, so we need to add classes such as Scanner and Photograph, along with any other classes we added during this part

**Comment by Ajaggi24** [comment]
did crc cards and uml as well only making sure the arrows are consistent
