### ISSUE TITLE
US 02.02.01 As an owner, I want to see the total estimated value of the shown items in the list of items.

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#54]

**Comment by Silin5** [comment]
Karl completed this.

**Comment by vinuyakarl** [comment]
First milestone: get the total value of existing items

**Comment by vinuyakarl** [comment]
Second milestone: When new items are added or deleted, the value is updated.

**Comment by vinuyakarl** [comment]
Third milestone: Firestore is implemented with the item list, so get the value of all items from Firestore.
