### ISSUE TITLE
Create Change Logo Page

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#79]

**Comment by Ajaggi24** [comment]
done

**Comment by Ajaggi24** [comment]
have finished the change logo only homebutton is taking back to additem need to look into that

**Comment by Ajaggi24** [comment]
Allow users to change the logo of a particular item.
- Toggle to  the image gallery to select a new logo for the item.
-Update the item page to display the new logo.
