### ISSUE TITLE
Finish Backlog Updates

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#95]
Due to TA feedback, we fell behind on some of our backlog information.

We will be reviewing all our previous, and current backlog information to make sure its completed properly

**Comment by CohenCalvert** [comment]
Finish all of my (Cohen) Backlog updates for past portions

**Comment by vinuyakarl** [comment]
Karl: Finished all of my updates as well.

**Comment by Silin5** [comment]
Silin: Finished all my updates as well!

**Comment by CohenCalvert** [comment]
All Previously missed updates have been finished! Will be lastly looking ahead at our next backlog for part 4

**Comment by CohenCalvert** [comment]
Everything is finished
