### ISSUE TITLE
US 02.05.01 As an owner, I want to filter the list of items by date range.

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#97]
This functionality is planned to be controlled by our HomescreenActivity. We have a button to allow the super to select a form of "filtering".

When a specific type (in this case, date range) is clicked, it will only display those items in the view screen

Updates to follow in comments below:

**Comment by vinuyakarl** [comment]
Milestone 1: Users can choose start and end date

**Comment by vinuyakarl** [comment]
Milestone 2: Chosen dates will filter out the items
