### ISSUE TITLE
US 02.06.01 As an owner, I want to filter the list of items by description keywords.

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#98]
Similar to other Filter Stories, each one will use the same general system. The Home screen will allow the user to select by which form they would like to filter their items. (in this case the keyword)

We are still undecided how we plan to handle keywords, if we plan to only look at one keyword, separate keywords by spaces, ect.
This will be discussed and commented upon in the comments of this story

Updates below:

**Comment by vinuyakarl** [comment]
Milestone 1: Users can type keywords and it'll display items that have that word in their description
