### ISSUE TITLE
US 02.07.01 As an owner, I want to filter the list of items by make.

### ISSUE THREAD

**Issue by CohenCalvert** [CMPUT301F23T24/KeepItAll#99]
Similar to other Filter Stories, each one will use the same general system. The Home screen will allow the user to select by which form they would like to filter their items. (in this case the make)

Once items are filtered, only those items will be visible on the homescreen.

Please view comments for updates and progress:

**Comment by vinuyakarl** [comment]
Milestone 1: Users can type a make and it'll display items that have that make in them
